Dev/petrakis/master/idetect 3475
blackducksoftware/integration-common pull request #40
Opened 2022-09-14 20:47 UTC by jppetrakis

2022-09-14 20:51 UTC, jppetrakis commented
This change should be a no-op for other usages of the ResilientJobConfig.  This also adds the capability to disable the progressive poll scheduling and simultaneously change the default constant polling interval using a Java system property.  The usage of the new constructor provided that will allow the usage of progressive polling will be done in synopsys-detect upon approval.

2022-09-20 13:56 UTC, stevebillings requested changes

2022-09-20 14:28 UTC, jppetrakis commented on src/main/java/com/synopsys/integration/wait/ResilientJobConfig.java
> +    private String flatInterval = System.getProperty(POLLING_INTERVAL_PROPERTY);
As it so happens this isn't necessary to do at this time so it can be removed.

2022-09-21 18:02 UTC, DanaMaxfield requested changes

2022-09-21 18:02 UTC, DanaMaxfield commented on src/main/java/com/synopsys/integration/wait/ResilientJobConfig.java
> +        }
Can't this be simplified to:
```
int now = 1;
if (prev1 != 0 || prev2 != -1) {
   now = prev1 + prev2;
}
```

If you'd rather the clarity of the if/else, then `now` should be initialized to `max`.

2022-09-21 18:24 UTC, jppetrakis commented on src/main/java/com/synopsys/integration/wait/ResilientJobConfig.java
> +        }
It really makes no difference what now is initialized to since it will get rewritten each time.  The method produces the true Fibonacci sequence if you set prev1 to 0 and prev2 to -1.  That is why there is a distinction in the calculation of "now".  Since the sequence 1, 1, 2, 3, 5... would seem odd in this case I set the values of prev1 and prev2 accordingly to produce 1, 2, 3, 5... etc.

2022-09-21 18:34 UTC, jppetrakis commented on src/main/java/com/synopsys/integration/wait/ResilientJobConfig.java
> +        }
pushed changes just now.  Thanks.

2022-09-21 20:05 UTC, DanaMaxfield approved these changes

2022-09-22 19:19 UTC, merged